##
## Coursera Data Science Specialization
## Course: Exploratory Data Analysis
## Course Instance: exdata-034
## Assignment: Course Project 1
## Student: Fabio Correa (feamcor)
##

rm(list = ls())
source("install_dependencies.R")
source("get_dataset.R")

# install_dependencies("???")
# library(???)

script.name <- "plot1"
start.time <- Sys.time()
start.time.text <- format(start.time, "_%Y%m%d_%H%M%S")
message(paste(Sys.time(), "Script started! timezone =", Sys.timezone()))

dataset <- get_dataset()

filename <- paste0(script.name, ".png")
png(file = filename, width = 480, height = 480, units = "px")
hist(dataset$Global_active_power,
     main = "Global Active Power",
     xlab = "Global Active Power (kilowatts)",
     ylab = "Frequency", col = "red", border = "black")
# add evidence in the graph that it was generated by this script
par(oma  = c(0,0,0,1), cex.sub = 0.25)
mtext(paste("exdata-034 feamcor", script.name, start.time.text), side = 4, outer = TRUE)
dev.off()
message(paste(Sys.time(), "Plot generated!", filename))
