##
## Coursera Data Science Specialization
## Course: Exploratory Data Analysis
## Course Instance: exdata-034
## Assignment: Course Project 1
## Student: Fabio Correa (feamcor)
##

rm(list = ls())
source("install_dependencies.R")

#
# ATTENTION!
#
# Considering that the dataset for all plot scripts is the same,
# please refer to the generic script below in order to understand
# how the dataset is downloaded, unzipped, read and modified accordingly.
#
source("get_dataset.R")

# install_dependencies("???")
# library(???)

script.name <- "plot3"
start.time <- Sys.time()
start.time.text <- format(start.time, "_%Y%m%d_%H%M%S")
message(paste(Sys.time(), "Script started! timezone =", Sys.timezone()))

dataset <- get_dataset()

filename <- paste0(script.name, ".png")
png(file = filename, width = 480, height = 480, units = "px")
plot(dataset$DateTime,
     dataset$Sub_metering_1,
     type = "l",
     col = "black",
     xlab = "",
     ylab = "Energy sub metering")
points(dataset$DateTime, dataset$Sub_metering_2, type = "l", col = "red")
points(dataset$DateTime, dataset$Sub_metering_3, type = "l", col = "blue")
legend("topright",
       lty = c(1, 1, 1),
       col = c("black", "red", "blue"),
       legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
# add evidence in the graph that it was generated by this script
par(oma  = c(0,0,0,1), cex.sub = 0.25)
mtext(paste("exdata-034 feamcor", script.name, start.time.text), side = 4, outer = TRUE)
dev.off()
message(paste(Sys.time(), "Plot generated!", filename))
